### ISSUE TITLE
Unable to support video uploading

### ISSUE THREAD

**Issue by dingyuchen** [dingyuchen/bugreporting#1]
https://raw.githubusercontent.com/dingyuchen/bugreporting/main/files/2fb1b0d5-adeb-4ca6-a0e6-0a6f52261849.mp4

**Comment by dingyuchen** [comment]
https://user-images.githubusercontent.com/9072299/110595657-41ee4800-81b9-11eb-9db7-1278dd1bacce.mp4

comments

**Comment by dingyuchen** [comment]
https://file-examples-com.github.io/uploads/2017/04/file_example_MP4_1920_18MG.mp4

**Comment by kkangs0226** [comment]
test

https://user-images.githubusercontent.com/66008784/110715321-f763de80-823f-11eb-988e-4f9de560a38d.mp4

<img width="215" alt="Screenshot 2021-03-11 at 7 57 45 AM" src="https://user-images.githubusercontent.com/66008784/110715351-064a9100-8240-11eb-8094-eae50fcb0e1c.png">

**Comment by dingyuchen** [comment]
<video width="215" controls>
<source src="https://raw.githubusercontent.com/dingyuchen/bugreporting/main/files/2fb1b0d5-adeb-4ca6-a0e6-0a6f52261849.mp4" type="video/mp4">
video preview
</video>
